name: Python api tests

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - 'master'
env:
  localhost: http://127.0.0.1:5000


jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
            python-version: 3.12
      - name: Install dependencies
        run: |
            python3 -m pip install --upgrade pip
            pip install Flask
            pip install requests
            pip install -r requirements.txt
      - name: Run tests
        run:
#            python3 app.py
            python3 -m  unittest


    
