name: Python api tests

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - 'master'
#env:
#  localhost: http://127.0.0.1:5000


jobs:
  Build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
            python-version: 3.12

      - name: Virtual Env
        run: |
          sudo apt install python3.12-venv -y
          python3 -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
            python3 -m pip install --upgrade pip
            pip install Flask
            pip install requests
#            pip install jsonify

      - name: Create Db
        run: |
          python3 create_database.py
#          python3 app.py
          python3 -m  unittest



    
