name: Python api tests

on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
            python-version: 3.12
      - name: Run tests
        run: python3  tests.py
